config/routes.rb
Rails.application.routes.draw do
  get 'item/page'
  resources :menus
  devise_for :users
  root 'home#page'

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/menu.rb
class Menu < ApplicationRecord
    belongs_to :user
    has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :menus
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
  end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  def page
    @menus = Menu.all
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # before_action :set_menu, only: %i[:show edit update destroy ]
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus or /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1 or /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus or /menus.json
  def create
    @menu = Menu.new(menu_params)
    @menu.user_id = current_user.id

    respond_to do |format|
      if @menu.save
        format.html { redirect_to menu_url(@menu), notice: "Menu was successfully created." }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1 or /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to menu_url(@menu), notice: "Menu was successfully updated." }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1 or /menus/1.json
  def destroy
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url, notice: "Menu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:name, :description, :price, :availability, :category, :user_id, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/home/page.html.erb
    <div class="jumbotron">
    <div class="row">
        <div class="col-md-6">
             <h1 class="display-4">Chalk Board Cafe! </h1>
             <p class="lead">Bites between the classes! </p>
            <hr class="my-4">
            <p class="lead">
                <%= link_to "Add menu", new_menu_path, class:"btn btn-primary btn-lg" %>
            </p>
            <p class="lead">
                <%= link_to "Show menu", item_page_path, class:"btn btn-primary btn-lg" %>
            </p>
        </div>

        <div class="col-md-6">
        <%=image_tag "cafe", class: "home-image"%>
        </div>

    </div>
</div>

app/views/item/page.html.erb
<div class="row">
    <% @menus.each do |menu| %>
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
            <%= image_tag menu.picture, class:"card-img-top"%>
            <div class="card-body">
                <h5 class="card-title"><%= menu.name %></h5>
                <p class="card-text menu-description"><%= menu.description%></p>
                <p class="card-text">$<%= menu.price%> 
                <%= link_to "Show More", menu_path(menu.id), class:"btn btn-primary btn-right" %>
                </p>
                
        </div>
     </div>
    </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chalkboradcafe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
    <%= render "partials/navbar" %>
      <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/menus/_form.html.erb
<%= simple_form_for(@menu) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :availability %>
    <%= f.input :category, collection: ["Meal", "Snack", "Breakfast"] %>
    <%=f.file_field :picture%>
   
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/menus/_menu.html.erb
<div id="<%= dom_id menu %>">
  <p>
    <strong>Name:</strong>
    <%= menu.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= menu.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= menu.price %>
  </p>

  <p>
    <strong>Availability:</strong>
    <%= menu.availability %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= menu.category %>
  </p>

  <p>
    <strong>User:</strong>
    <%= menu.user %>
  </p>

  <p>
    <strong>References:</strong>
    <%= menu.references %>
  </p>

</div>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Show", @menu %> |
  <%= link_to "Back", menus_path %>
</div>

app/views/menus/index.html.erb
<p style="notice"><%= notice %></p>

<h1>Menus</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Availability</th>
      <th>Category</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.name %></td>
        <td><%= menu.description %></td>
        <td><%= menu.price %></td>
        <td><%= menu.availability %></td>
        <td><%= menu.category %></td>
        <td><%= menu.user_id %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Back", menus_path %>
</div>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @menu.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu.price %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @menu.availability %>
</p>

<p>
  <strong>Category:</strong>
  <%= @menu.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @menu.user.email %>
</p>
<p>
<%= image_tag @menu.picture%>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">ChalkBoard Cafe</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
      <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% end %>
      </li>
    </ul>
  </div>
</nav>